---
- hosts: all
  become: true
  roles:
    - awx_k3s
  environment:
    NAMESPACE: awx
  vars_prompt:
    - name: k3s_version
      prompt: Enter k3s version
      default: v1.33.4+k3s1
      private: false

    - name: operator_version
      prompt: Enter version number for awx operator
      default: 2.19.1
      private: false

    - name: awx_version
      prompt: Which version of AWXai do you want to install?
      default: 25.0.1
      private: false

    - name: namespace_k3s
      prompt: Set namespace for deployment
      default: awxai
      private: false

    - name: awx_admin_password
      prompt: Enter web interface password
      default: LhTAKSFgTgLynAljakvkdLueVgNUXsQG

    - name: postgres_password
      prompt: Enter postgres database password
      default: mydbpasswd

    - name: awx_hostname
      prompt: Set a hostname/FQDN for your AWXai instance
      default: awxai.antuelle78.com
      private: false
