---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    stategy:
      matrix:
        distro:
          - centos8
          - ubuntu20.04

  steps:
    - name: Check out codebase.
      uses: actions/checkout@v3

    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install test dependencies.
      run: pip3 install molecule docker yamllint ansible-lint

    - name: Run molecule tests
      run: molecule test
